"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dh$#1&6xsbpei#za+lko6pqq=hz@@p%-bo7w@be%v51db8ve!2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '172.31.12.2',
    '18.235.57.99',
    '34.233.106.112',
    '172.31.25.73',
    '54.209.49.172',
    '172.31.89.157',
    'crowd.cs.purdue.edu',
    'yuchun.org',
    'www.yuchun.org',
    'devil-dev.us-east-1.elasticbeanstalk.com',
    '172.31.6.115',
    'devil-advocate.hci-study.com',
    'www.devil-advocate.hci-study.com',
    'http://group-discussion-experiment.us-east-2.elasticbeanstalk.com',
    'www.group-discussion-experiment.us-east-2.elasticbeanstalk.com',
    'gobackend.discussionexperiment.com',
    'www.gobackend.discussionexperiment.com',
    'https://main.d3lbr0m46vlu6t.amplifyapp.com',
    'www.main.d3lbr0m46vlu6t.amplifyapp.com',
    'https://main.d93mhbbvrb5dl.amplifyapp.com',
    'www.main.d93mhbbvrb5dl.amplifyapp.com',
    '172.31.16.110',
    '172.31.31.69',
    '172.31.19.97',
    '100.116.133.2:8000',
    'main.d1lwa086vbiduv.amplifyapp.com',
    'www.main.d1lwa086vbiduv.amplifyapp.com',
    'https://main.d1lwa086vbiduv.amplifyapp.com',
    'www.main.d1lwa086vbiduv.amplifyapp.com',
    'main.d8zzmpev39qs6.amplifyapp.com',
    'www.main.d8zzmpev39qs6.amplifyapp.com',
    'https://main.d8zzmpev39qs6.amplifyapp.com',
    'www.main.d8zzmpev39qs6.amplifyapp.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'experiment',
    'rest_framework',
    'channels'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'server.middleware.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'server.middleware.xframe_options_middleware.XFrameOptionsMiddleware',  # Custom X-Frame-Options middleware
]

# CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-request-id',
    'x-request-id',
    'x-requested-with',
    'content-type',
    'accept',
    'origin',
    'authorization',
    'x-csrftoken'
]

CORS_ORIGIN_WHITELIST = [
    'http://127.0.0.1:8080',
    'https://127.0.0.1:8080',
    'https://main.d93mhbbvrb5dl.amplifyapp.com',
    'https://main.d3lbr0m46vlu6t.amplifyapp.com',
    'https://main.d1lwa086vbiduv.amplifyapp.com',
    'https://main.d8zzmpev39qs6.amplifyapp.com',
    'http://localhost:8080',
    'http://localhost:3000',
    'http://localhost:8000',
    'https://gobackend.discussionexperiment.com'
]

# CORS settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Add this to ensure preflight requests are handled properly
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_EXPOSE_HEADERS = [
    'x-request-id',
    'x-requested-with',
    'content-type',
    'accept',
    'origin',
    'authorization',
    'x-csrftoken'
]

# X-Frame-Options settings - handled by our custom middleware
X_FRAME_OPTIONS = 'DENY'  # Default deny, overridden by our middleware

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'
ASGI_APPLICATION = 'server.asgi.application'

if 'REDIS_URL' in os.environ:
    CHANNEL_LAYERS = {
        'default' : {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [
                    (os.environ["REDIS_URL"], 6379),
                ],
            }
        }
    }
else:
    CHANNEL_LAYERS = {
        'default' : {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                # "hosts": [('aws-my-1p3rgt1ppy60m.meelff.0001.use1.cache.amazonaws.com', 6379)],
                "hosts": [('localhost', 6379)],
            },
        }
    }



# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
if 'RDS_DB_NAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'experimentai',
            'USER': 'myz',
            'PASSWORD': 'myzbest',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }


# Sqlite database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CORS_ALLOW_ALL_ORIGINS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "www", "static")
STATIC_URL = '/static/'

# Test Mode
TEST_MODE = os.environ.get('TEST_MODE', 'False').lower() == 'true'

# Ensure logs directory exists
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# Logging configuration
def get_logging_config():
    """Return the appropriate logging configuration based on the environment."""
    if DEBUG:
        # In development, only log from the main process to avoid duplicates
        if os.environ.get('RUN_MAIN') or not os.environ.get('WERKZEUG_RUN_MAIN'):
            console_handler = 'console'
        else:
            console_handler = 'null'
    else:
        # In production, log everything
        console_handler = 'console'

    return {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
            'detailed': {
                'format': '{asctime} - {name} - {levelname} - {message}',
                'style': '{',
            },
        },
        'handlers': {
            'null': {
                'class': 'logging.NullHandler',
            },
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
            'file': {
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': os.path.join(LOG_DIR, 'django.log'),
                'maxBytes': 1024*1024*5,  # 5 MB
                'backupCount': 5,
                'formatter': 'detailed',
                'encoding': 'utf8',
            },
        },
        'root': {
            'handlers': [console_handler, 'file'],
            'level': 'INFO',
        },
        'loggers': {
            'experiment': {
                'handlers': [console_handler, 'file'],
                'level': 'INFO',
                'propagate': False,
            },
            'channels': {
                'handlers': [console_handler, 'file'],
                'level': 'DEBUG' if DEBUG else 'INFO',
                'propagate': False,
            },
            'django': {
                'handlers': [console_handler, 'file'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

# Apply the logging configuration
LOGGING = get_logging_config()
